// Generated by gencpp from file autobots_calibration/CameraExtrinsics.msg
// DO NOT EDIT!


#ifndef AUTOBOTS_CALIBRATION_MESSAGE_CAMERAEXTRINSICS_H
#define AUTOBOTS_CALIBRATION_MESSAGE_CAMERAEXTRINSICS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace autobots_calibration
{
template <class ContainerAllocator>
struct CameraExtrinsics_
{
  typedef CameraExtrinsics_<ContainerAllocator> Type;

  CameraExtrinsics_()
    : header()
    , M_CL()  {
      M_CL.assign(0.0);
  }
  CameraExtrinsics_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , M_CL()  {
  (void)_alloc;
      M_CL.assign(0.0);
  }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef boost::array<double, 16>  _M_CL_type;
  _M_CL_type M_CL;





  typedef boost::shared_ptr< ::autobots_calibration::CameraExtrinsics_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::autobots_calibration::CameraExtrinsics_<ContainerAllocator> const> ConstPtr;

}; // struct CameraExtrinsics_

typedef ::autobots_calibration::CameraExtrinsics_<std::allocator<void> > CameraExtrinsics;

typedef boost::shared_ptr< ::autobots_calibration::CameraExtrinsics > CameraExtrinsicsPtr;
typedef boost::shared_ptr< ::autobots_calibration::CameraExtrinsics const> CameraExtrinsicsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::autobots_calibration::CameraExtrinsics_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::autobots_calibration::CameraExtrinsics_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::autobots_calibration::CameraExtrinsics_<ContainerAllocator1> & lhs, const ::autobots_calibration::CameraExtrinsics_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.M_CL == rhs.M_CL;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::autobots_calibration::CameraExtrinsics_<ContainerAllocator1> & lhs, const ::autobots_calibration::CameraExtrinsics_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace autobots_calibration

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::autobots_calibration::CameraExtrinsics_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::autobots_calibration::CameraExtrinsics_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::autobots_calibration::CameraExtrinsics_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::autobots_calibration::CameraExtrinsics_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::autobots_calibration::CameraExtrinsics_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::autobots_calibration::CameraExtrinsics_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::autobots_calibration::CameraExtrinsics_<ContainerAllocator> >
{
  static const char* value()
  {
    return "41b9370e4bc1b05648a3ac16f68f4613";
  }

  static const char* value(const ::autobots_calibration::CameraExtrinsics_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x41b9370e4bc1b056ULL;
  static const uint64_t static_value2 = 0x48a3ac16f68f4613ULL;
};

template<class ContainerAllocator>
struct DataType< ::autobots_calibration::CameraExtrinsics_<ContainerAllocator> >
{
  static const char* value()
  {
    return "autobots_calibration/CameraExtrinsics";
  }

  static const char* value(const ::autobots_calibration::CameraExtrinsics_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::autobots_calibration::CameraExtrinsics_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"\n"
"# flattened 4x4 matrix representing the camera extrinsics\n"
"float64[16] M_CL\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::autobots_calibration::CameraExtrinsics_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::autobots_calibration::CameraExtrinsics_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.M_CL);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CameraExtrinsics_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::autobots_calibration::CameraExtrinsics_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::autobots_calibration::CameraExtrinsics_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "M_CL[]" << std::endl;
    for (size_t i = 0; i < v.M_CL.size(); ++i)
    {
      s << indent << "  M_CL[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.M_CL[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUTOBOTS_CALIBRATION_MESSAGE_CAMERAEXTRINSICS_H
